//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DecisionWrapperCsharp {

public class AlfaBetaInfo : DecisionMakerInfo {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal AlfaBetaInfo(global::System.IntPtr cPtr, bool cMemoryOwn) : base(libdesPINVOKE.AlfaBetaInfo_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AlfaBetaInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(AlfaBetaInfo obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libdesPINVOKE.delete_AlfaBetaInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public AlfaBetaInfo() : this(libdesPINVOKE.new_AlfaBetaInfo__SWIG_0(), true) {
  }

  public AlfaBetaInfo(double alfa, double beta) : this(libdesPINVOKE.new_AlfaBetaInfo__SWIG_1(alfa, beta), true) {
  }

  public double getAlfa() {
    double ret = libdesPINVOKE.AlfaBetaInfo_getAlfa(swigCPtr);
    return ret;
  }

  public double getBeta() {
    double ret = libdesPINVOKE.AlfaBetaInfo_getBeta(swigCPtr);
    return ret;
  }

  public bool isValid() {
    bool ret = libdesPINVOKE.AlfaBetaInfo_isValid(swigCPtr);
    return ret;
  }

  public override string toString() {
    string ret = libdesPINVOKE.AlfaBetaInfo_toString(swigCPtr);
    return ret;
  }

}

}
