//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace MultiCriteriaCsharpApi {

public class ConcordanceDisconcordanceThresholds : DecisionMakerInfo {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal ConcordanceDisconcordanceThresholds(global::System.IntPtr cPtr, bool cMemoryOwn) : base(libdesPINVOKE.ConcordanceDisconcordanceThresholds_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ConcordanceDisconcordanceThresholds obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ConcordanceDisconcordanceThresholds obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libdesPINVOKE.delete_ConcordanceDisconcordanceThresholds(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public ConcordanceDisconcordanceThresholds() : this(libdesPINVOKE.new_ConcordanceDisconcordanceThresholds__SWIG_0(), true) {
  }

  public ConcordanceDisconcordanceThresholds(double strongConcordanceThreshold, double meanConcordanceThreshold, double weakConcordanceThreshold, double strongDiscordanceThreshold, double weakDiscordanceThreshold) : this(libdesPINVOKE.new_ConcordanceDisconcordanceThresholds__SWIG_1(strongConcordanceThreshold, meanConcordanceThreshold, weakConcordanceThreshold, strongDiscordanceThreshold, weakDiscordanceThreshold), true) {
  }

  public double getStrongConcordanceThreshold() {
    double ret = libdesPINVOKE.ConcordanceDisconcordanceThresholds_getStrongConcordanceThreshold(swigCPtr);
    return ret;
  }

  public double getMeanConcordanceThreshold() {
    double ret = libdesPINVOKE.ConcordanceDisconcordanceThresholds_getMeanConcordanceThreshold(swigCPtr);
    return ret;
  }

  public double getWeakConcordanceThreshold() {
    double ret = libdesPINVOKE.ConcordanceDisconcordanceThresholds_getWeakConcordanceThreshold(swigCPtr);
    return ret;
  }

  public double getStrongDiscordanceThreshold() {
    double ret = libdesPINVOKE.ConcordanceDisconcordanceThresholds_getStrongDiscordanceThreshold(swigCPtr);
    return ret;
  }

  public double getWeakDiscordanceThreshold() {
    double ret = libdesPINVOKE.ConcordanceDisconcordanceThresholds_getWeakDiscordanceThreshold(swigCPtr);
    return ret;
  }

  public bool isValid() {
    bool ret = libdesPINVOKE.ConcordanceDisconcordanceThresholds_isValid(swigCPtr);
    return ret;
  }

  public override string toString() {
    string ret = libdesPINVOKE.ConcordanceDisconcordanceThresholds_toString(swigCPtr);
    return ret;
  }

}

}
