//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DecisionWrapperCsharp {

public class CriteriaRelationConverter : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CriteriaRelationConverter(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CriteriaRelationConverter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CriteriaRelationConverter obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CriteriaRelationConverter() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libdesPINVOKE.delete_CriteriaRelationConverter(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public static AllCriteriaRelation convertToAllCriteriaRelation(CriteriaRelation relation, bool verbose) {
    global::System.IntPtr cPtr = libdesPINVOKE.CriteriaRelationConverter_convertToAllCriteriaRelation__SWIG_0(CriteriaRelation.getCPtr(relation), verbose);
    AllCriteriaRelation ret = (cPtr == global::System.IntPtr.Zero) ? null : new AllCriteriaRelation(cPtr, false);
    return ret;
  }

  public static AllCriteriaRelation convertToAllCriteriaRelation(CriteriaRelation relation) {
    global::System.IntPtr cPtr = libdesPINVOKE.CriteriaRelationConverter_convertToAllCriteriaRelation__SWIG_1(CriteriaRelation.getCPtr(relation));
    AllCriteriaRelation ret = (cPtr == global::System.IntPtr.Zero) ? null : new AllCriteriaRelation(cPtr, false);
    return ret;
  }

  public static SimpleCriteriaRelation convertToSimpleCriteriaRelation(CriteriaRelation relation, bool verbose) {
    global::System.IntPtr cPtr = libdesPINVOKE.CriteriaRelationConverter_convertToSimpleCriteriaRelation__SWIG_0(CriteriaRelation.getCPtr(relation), verbose);
    SimpleCriteriaRelation ret = (cPtr == global::System.IntPtr.Zero) ? null : new SimpleCriteriaRelation(cPtr, false);
    return ret;
  }

  public static SimpleCriteriaRelation convertToSimpleCriteriaRelation(CriteriaRelation relation) {
    global::System.IntPtr cPtr = libdesPINVOKE.CriteriaRelationConverter_convertToSimpleCriteriaRelation__SWIG_1(CriteriaRelation.getCPtr(relation));
    SimpleCriteriaRelation ret = (cPtr == global::System.IntPtr.Zero) ? null : new SimpleCriteriaRelation(cPtr, false);
    return ret;
  }

  public static WeightCriteriaRelation convertToWeightCriteriaRelation(CriteriaRelation relation, bool verbose) {
    global::System.IntPtr cPtr = libdesPINVOKE.CriteriaRelationConverter_convertToWeightCriteriaRelation__SWIG_0(CriteriaRelation.getCPtr(relation), verbose);
    WeightCriteriaRelation ret = (cPtr == global::System.IntPtr.Zero) ? null : new WeightCriteriaRelation(cPtr, false);
    return ret;
  }

  public static WeightCriteriaRelation convertToWeightCriteriaRelation(CriteriaRelation relation) {
    global::System.IntPtr cPtr = libdesPINVOKE.CriteriaRelationConverter_convertToWeightCriteriaRelation__SWIG_1(CriteriaRelation.getCPtr(relation));
    WeightCriteriaRelation ret = (cPtr == global::System.IntPtr.Zero) ? null : new WeightCriteriaRelation(cPtr, false);
    return ret;
  }

}

}
