//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DecisionWrapperCsharp {

public class Criterias : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<Criteria>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Criterias(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Criterias obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Criterias obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Criterias() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libdesPINVOKE.delete_Criterias(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Criterias(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Criteria element in c) {
      this.Add(element);
    }
  }

  public Criterias(global::System.Collections.Generic.IEnumerable<Criteria> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Criteria element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public Criteria this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(Criteria[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(Criteria[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, Criteria[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public Criteria[] ToArray() {
    Criteria[] array = new Criteria[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<Criteria> global::System.Collections.Generic.IEnumerable<Criteria>.GetEnumerator() {
    return new CriteriasEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new CriteriasEnumerator(this);
  }

  public CriteriasEnumerator GetEnumerator() {
    return new CriteriasEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class CriteriasEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<Criteria>
  {
    private Criterias collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public CriteriasEnumerator(Criterias collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public Criteria Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (Criteria)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public Criterias() : this(libdesPINVOKE.new_Criterias__SWIG_0(), true) {
  }

  public Criterias(Criterias other) : this(libdesPINVOKE.new_Criterias__SWIG_1(Criterias.getCPtr(other)), true) {
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    libdesPINVOKE.Criterias_Clear(swigCPtr);
  }

  public void Add(Criteria x) {
    libdesPINVOKE.Criterias_Add(swigCPtr, Criteria.getCPtr(x));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = libdesPINVOKE.Criterias_size(swigCPtr);
    return ret;
  }

  private bool empty() {
    bool ret = libdesPINVOKE.Criterias_empty(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = libdesPINVOKE.Criterias_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    libdesPINVOKE.Criterias_reserve(swigCPtr, n);
  }

  public Criterias(int capacity) : this(libdesPINVOKE.new_Criterias__SWIG_2(capacity), true) {
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  private Criteria getitemcopy(int index) {
    Criteria ret = new Criteria(libdesPINVOKE.Criterias_getitemcopy(swigCPtr, index), true);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private Criteria getitem(int index) {
    Criteria ret = new Criteria(libdesPINVOKE.Criterias_getitem(swigCPtr, index), false);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, Criteria val) {
    libdesPINVOKE.Criterias_setitem(swigCPtr, index, Criteria.getCPtr(val));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(Criterias values) {
    libdesPINVOKE.Criterias_AddRange(swigCPtr, Criterias.getCPtr(values));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public Criterias GetRange(int index, int count) {
    global::System.IntPtr cPtr = libdesPINVOKE.Criterias_GetRange(swigCPtr, index, count);
    Criterias ret = (cPtr == global::System.IntPtr.Zero) ? null : new Criterias(cPtr, true);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, Criteria x) {
    libdesPINVOKE.Criterias_Insert(swigCPtr, index, Criteria.getCPtr(x));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, Criterias values) {
    libdesPINVOKE.Criterias_InsertRange(swigCPtr, index, Criterias.getCPtr(values));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    libdesPINVOKE.Criterias_RemoveAt(swigCPtr, index);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    libdesPINVOKE.Criterias_RemoveRange(swigCPtr, index, count);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public static Criterias Repeat(Criteria value, int count) {
    global::System.IntPtr cPtr = libdesPINVOKE.Criterias_Repeat(Criteria.getCPtr(value), count);
    Criterias ret = (cPtr == global::System.IntPtr.Zero) ? null : new Criterias(cPtr, true);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    libdesPINVOKE.Criterias_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    libdesPINVOKE.Criterias_Reverse__SWIG_1(swigCPtr, index, count);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, Criterias values) {
    libdesPINVOKE.Criterias_SetRange(swigCPtr, index, Criterias.getCPtr(values));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
