//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CriterionTypeList : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IList<CriterionType>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CriterionTypeList(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CriterionTypeList obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CriterionTypeList obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CriterionTypeList() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libdesPINVOKE.delete_CriterionTypeList(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public CriterionTypeList(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (CriterionType element in c) {
      this.Add(element);
    }
  }

  public CriterionTypeList(global::System.Collections.Generic.IEnumerable<CriterionType> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (CriterionType element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public CriterionType this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(CriterionType[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(CriterionType[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, CriterionType[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public CriterionType[] ToArray() {
    CriterionType[] array = new CriterionType[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<CriterionType> global::System.Collections.Generic.IEnumerable<CriterionType>.GetEnumerator() {
    return new CriterionTypeListEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new CriterionTypeListEnumerator(this);
  }

  public CriterionTypeListEnumerator GetEnumerator() {
    return new CriterionTypeListEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class CriterionTypeListEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<CriterionType>
  {
    private CriterionTypeList collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public CriterionTypeListEnumerator(CriterionTypeList collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public CriterionType Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (CriterionType)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public CriterionTypeList() : this(libdesPINVOKE.new_CriterionTypeList__SWIG_0(), true) {
  }

  public CriterionTypeList(CriterionTypeList other) : this(libdesPINVOKE.new_CriterionTypeList__SWIG_1(CriterionTypeList.getCPtr(other)), true) {
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    libdesPINVOKE.CriterionTypeList_Clear(swigCPtr);
  }

  public void Add(CriterionType x) {
    libdesPINVOKE.CriterionTypeList_Add(swigCPtr, CriterionType.getCPtr(x));
  }

  private uint size() {
    uint ret = libdesPINVOKE.CriterionTypeList_size(swigCPtr);
    return ret;
  }

  private bool empty() {
    bool ret = libdesPINVOKE.CriterionTypeList_empty(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = libdesPINVOKE.CriterionTypeList_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    libdesPINVOKE.CriterionTypeList_reserve(swigCPtr, n);
  }

  public CriterionTypeList(int capacity) : this(libdesPINVOKE.new_CriterionTypeList__SWIG_2(capacity), true) {
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  private CriterionType getitemcopy(int index) {
    global::System.IntPtr cPtr = libdesPINVOKE.CriterionTypeList_getitemcopy(swigCPtr, index);
    CriterionType ret = (cPtr == global::System.IntPtr.Zero) ? null : new CriterionType(cPtr, false);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private CriterionType getitem(int index) {
    global::System.IntPtr cPtr = libdesPINVOKE.CriterionTypeList_getitem(swigCPtr, index);
    CriterionType ret = (cPtr == global::System.IntPtr.Zero) ? null : new CriterionType(cPtr, false);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, CriterionType val) {
    libdesPINVOKE.CriterionTypeList_setitem(swigCPtr, index, CriterionType.getCPtr(val));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(CriterionTypeList values) {
    libdesPINVOKE.CriterionTypeList_AddRange(swigCPtr, CriterionTypeList.getCPtr(values));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public CriterionTypeList GetRange(int index, int count) {
    global::System.IntPtr cPtr = libdesPINVOKE.CriterionTypeList_GetRange(swigCPtr, index, count);
    CriterionTypeList ret = (cPtr == global::System.IntPtr.Zero) ? null : new CriterionTypeList(cPtr, true);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, CriterionType x) {
    libdesPINVOKE.CriterionTypeList_Insert(swigCPtr, index, CriterionType.getCPtr(x));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, CriterionTypeList values) {
    libdesPINVOKE.CriterionTypeList_InsertRange(swigCPtr, index, CriterionTypeList.getCPtr(values));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    libdesPINVOKE.CriterionTypeList_RemoveAt(swigCPtr, index);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    libdesPINVOKE.CriterionTypeList_RemoveRange(swigCPtr, index, count);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public static CriterionTypeList Repeat(CriterionType value, int count) {
    global::System.IntPtr cPtr = libdesPINVOKE.CriterionTypeList_Repeat(CriterionType.getCPtr(value), count);
    CriterionTypeList ret = (cPtr == global::System.IntPtr.Zero) ? null : new CriterionTypeList(cPtr, true);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    libdesPINVOKE.CriterionTypeList_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    libdesPINVOKE.CriterionTypeList_Reverse__SWIG_1(swigCPtr, index, count);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, CriterionTypeList values) {
    libdesPINVOKE.CriterionTypeList_SetRange(swigCPtr, index, CriterionTypeList.getCPtr(values));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(CriterionType value) {
    bool ret = libdesPINVOKE.CriterionTypeList_Contains(swigCPtr, CriterionType.getCPtr(value));
    return ret;
  }

  public int IndexOf(CriterionType value) {
    int ret = libdesPINVOKE.CriterionTypeList_IndexOf(swigCPtr, CriterionType.getCPtr(value));
    return ret;
  }

  public int LastIndexOf(CriterionType value) {
    int ret = libdesPINVOKE.CriterionTypeList_LastIndexOf(swigCPtr, CriterionType.getCPtr(value));
    return ret;
  }

  public bool Remove(CriterionType value) {
    bool ret = libdesPINVOKE.CriterionTypeList_Remove(swigCPtr, CriterionType.getCPtr(value));
    return ret;
  }

}
