//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CriteriaAggregationMethod : OneStepMethod {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal CriteriaAggregationMethod(global::System.IntPtr cPtr, bool cMemoryOwn) : base(libdesPINVOKE.CriteriaAggregationMethod_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CriteriaAggregationMethod obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CriteriaAggregationMethod obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libdesPINVOKE.delete_CriteriaAggregationMethod(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public CriteriaAggregationMethod(AggregationOperator aggregationOperator) : this(libdesPINVOKE.new_CriteriaAggregationMethod__SWIG_0(AggregationOperator.getCPtr(aggregationOperator)), true) {
  }

  public CriteriaAggregationMethod(AggregationOperator aggregationOperator, Normalizer normalizer) : this(libdesPINVOKE.new_CriteriaAggregationMethod__SWIG_1(AggregationOperator.getCPtr(aggregationOperator), Normalizer.getCPtr(normalizer)), true) {
  }

  public CriteriaAggregationMethod(MathModel mathModel, WeightCriteriaRelation relation, AggregationOperator aggregationOperator) : this(libdesPINVOKE.new_CriteriaAggregationMethod__SWIG_2(MathModel.getCPtr(mathModel), WeightCriteriaRelation.getCPtr(relation), AggregationOperator.getCPtr(aggregationOperator)), true) {
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public CriteriaAggregationMethod(MathModel mathModel, WeightCriteriaRelation relation, AggregationOperator aggregationOperator, Normalizer normalizer) : this(libdesPINVOKE.new_CriteriaAggregationMethod__SWIG_3(MathModel.getCPtr(mathModel), WeightCriteriaRelation.getCPtr(relation), AggregationOperator.getCPtr(aggregationOperator), Normalizer.getCPtr(normalizer)), true) {
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public override MathModel getMathModel() {
    MathModel ret = new MathModel(libdesPINVOKE.CriteriaAggregationMethod_getMathModel(swigCPtr), true);
    return ret;
  }

  public override void setMathModel(MathModel mathModel) {
    libdesPINVOKE.CriteriaAggregationMethod_setMathModel(swigCPtr, MathModel.getCPtr(mathModel));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public override void setCriteriaRelation(CriteriaRelation relation) {
    libdesPINVOKE.CriteriaAggregationMethod_setCriteriaRelation(swigCPtr, CriteriaRelation.getCPtr(relation));
  }

  public void setAggregationOperator(AggregationOperator aggregationOperator) {
    libdesPINVOKE.CriteriaAggregationMethod_setAggregationOperator(swigCPtr, AggregationOperator.getCPtr(aggregationOperator));
  }

  public void setNormalizer(Normalizer normalizer) {
    libdesPINVOKE.CriteriaAggregationMethod_setNormalizer(swigCPtr, Normalizer.getCPtr(normalizer));
  }

  public override SolveStatus solve() {
    SolveStatus ret = new SolveStatus(libdesPINVOKE.CriteriaAggregationMethod_solve(swigCPtr), true);
    return ret;
  }

  public WeightMap getEstimateVectorWeight() {
    WeightMap ret = new WeightMap(libdesPINVOKE.CriteriaAggregationMethod_getEstimateVectorWeight(swigCPtr), true);
    return ret;
  }

  public override EstimateVector getBestEstimateVector() {
    EstimateVector ret = new EstimateVector(libdesPINVOKE.CriteriaAggregationMethod_getBestEstimateVector(swigCPtr), true);
    return ret;
  }

  public override void withSolveProcessLog() {
    libdesPINVOKE.CriteriaAggregationMethod_withSolveProcessLog(swigCPtr);
  }

  public override TaskProcess getProcess() {
    TaskProcess ret = new TaskProcess(libdesPINVOKE.CriteriaAggregationMethod_getProcess(swigCPtr), true);
    return ret;
  }

}
