//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace MultiCriteriaCsharpApi {

public class EstimateVectors : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<EstimateVector>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal EstimateVectors(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(EstimateVectors obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(EstimateVectors obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~EstimateVectors() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libdesPINVOKE.delete_EstimateVectors(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public EstimateVectors(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (EstimateVector element in c) {
      this.Add(element);
    }
  }

  public EstimateVectors(global::System.Collections.Generic.IEnumerable<EstimateVector> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (EstimateVector element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public EstimateVector this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(EstimateVector[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(EstimateVector[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, EstimateVector[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public EstimateVector[] ToArray() {
    EstimateVector[] array = new EstimateVector[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<EstimateVector> global::System.Collections.Generic.IEnumerable<EstimateVector>.GetEnumerator() {
    return new EstimateVectorsEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new EstimateVectorsEnumerator(this);
  }

  public EstimateVectorsEnumerator GetEnumerator() {
    return new EstimateVectorsEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class EstimateVectorsEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<EstimateVector>
  {
    private EstimateVectors collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public EstimateVectorsEnumerator(EstimateVectors collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public EstimateVector Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (EstimateVector)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public EstimateVectors() : this(libdesPINVOKE.new_EstimateVectors__SWIG_0(), true) {
  }

  public EstimateVectors(EstimateVectors other) : this(libdesPINVOKE.new_EstimateVectors__SWIG_1(EstimateVectors.getCPtr(other)), true) {
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    libdesPINVOKE.EstimateVectors_Clear(swigCPtr);
  }

  public void Add(EstimateVector x) {
    libdesPINVOKE.EstimateVectors_Add(swigCPtr, EstimateVector.getCPtr(x));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = libdesPINVOKE.EstimateVectors_size(swigCPtr);
    return ret;
  }

  private bool empty() {
    bool ret = libdesPINVOKE.EstimateVectors_empty(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = libdesPINVOKE.EstimateVectors_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    libdesPINVOKE.EstimateVectors_reserve(swigCPtr, n);
  }

  public EstimateVectors(int capacity) : this(libdesPINVOKE.new_EstimateVectors__SWIG_2(capacity), true) {
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  private EstimateVector getitemcopy(int index) {
    EstimateVector ret = new EstimateVector(libdesPINVOKE.EstimateVectors_getitemcopy(swigCPtr, index), true);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private EstimateVector getitem(int index) {
    EstimateVector ret = new EstimateVector(libdesPINVOKE.EstimateVectors_getitem(swigCPtr, index), false);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, EstimateVector val) {
    libdesPINVOKE.EstimateVectors_setitem(swigCPtr, index, EstimateVector.getCPtr(val));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(EstimateVectors values) {
    libdesPINVOKE.EstimateVectors_AddRange(swigCPtr, EstimateVectors.getCPtr(values));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public EstimateVectors GetRange(int index, int count) {
    global::System.IntPtr cPtr = libdesPINVOKE.EstimateVectors_GetRange(swigCPtr, index, count);
    EstimateVectors ret = (cPtr == global::System.IntPtr.Zero) ? null : new EstimateVectors(cPtr, true);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, EstimateVector x) {
    libdesPINVOKE.EstimateVectors_Insert(swigCPtr, index, EstimateVector.getCPtr(x));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, EstimateVectors values) {
    libdesPINVOKE.EstimateVectors_InsertRange(swigCPtr, index, EstimateVectors.getCPtr(values));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    libdesPINVOKE.EstimateVectors_RemoveAt(swigCPtr, index);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    libdesPINVOKE.EstimateVectors_RemoveRange(swigCPtr, index, count);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public static EstimateVectors Repeat(EstimateVector value, int count) {
    global::System.IntPtr cPtr = libdesPINVOKE.EstimateVectors_Repeat(EstimateVector.getCPtr(value), count);
    EstimateVectors ret = (cPtr == global::System.IntPtr.Zero) ? null : new EstimateVectors(cPtr, true);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    libdesPINVOKE.EstimateVectors_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    libdesPINVOKE.EstimateVectors_Reverse__SWIG_1(swigCPtr, index, count);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, EstimateVectors values) {
    libdesPINVOKE.EstimateVectors_SetRange(swigCPtr, index, EstimateVectors.getCPtr(values));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
