//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DecisionWrapperCsharp {

public class IdealDistanceAggregationOperator : AggregationOperator {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal IdealDistanceAggregationOperator(global::System.IntPtr cPtr, bool cMemoryOwn) : base(libdesPINVOKE.IdealDistanceAggregationOperator_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IdealDistanceAggregationOperator obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IdealDistanceAggregationOperator obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libdesPINVOKE.delete_IdealDistanceAggregationOperator(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public override WeightMap getEstimateVectorMark(MathModel mathModel, WeightCriteriaRelation weightCriteriaRelation) {
    WeightMap ret = new WeightMap(libdesPINVOKE.IdealDistanceAggregationOperator_getEstimateVectorMark(swigCPtr, MathModel.getCPtr(mathModel), WeightCriteriaRelation.getCPtr(weightCriteriaRelation)), true);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override double getBestValue() {
    double ret = libdesPINVOKE.IdealDistanceAggregationOperator_getBestValue(swigCPtr);
    return ret;
  }

  public override int getBestEstimateVectorNum() {
    int ret = libdesPINVOKE.IdealDistanceAggregationOperator_getBestEstimateVectorNum(swigCPtr);
    return ret;
  }

  public override bool isNeedNormalizedMathModel() {
    bool ret = libdesPINVOKE.IdealDistanceAggregationOperator_isNeedNormalizedMathModel(swigCPtr);
    return ret;
  }

  public IdealDistanceAggregationOperator() : this(libdesPINVOKE.new_IdealDistanceAggregationOperator(), true) {
  }

}

}
