//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace MultiCriteriaCsharpApi {

public class IndifferencePreferenceVeto : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IndifferencePreferenceVeto(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IndifferencePreferenceVeto obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IndifferencePreferenceVeto obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~IndifferencePreferenceVeto() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libdesPINVOKE.delete_IndifferencePreferenceVeto(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public double indifference {
    set {
      libdesPINVOKE.IndifferencePreferenceVeto_indifference_set(swigCPtr, value);
    } 
    get {
      double ret = libdesPINVOKE.IndifferencePreferenceVeto_indifference_get(swigCPtr);
      return ret;
    } 
  }

  public double preference {
    set {
      libdesPINVOKE.IndifferencePreferenceVeto_preference_set(swigCPtr, value);
    } 
    get {
      double ret = libdesPINVOKE.IndifferencePreferenceVeto_preference_get(swigCPtr);
      return ret;
    } 
  }

  public double veto {
    set {
      libdesPINVOKE.IndifferencePreferenceVeto_veto_set(swigCPtr, value);
    } 
    get {
      double ret = libdesPINVOKE.IndifferencePreferenceVeto_veto_get(swigCPtr);
      return ret;
    } 
  }

  public IndifferencePreferenceVeto(double indifference, double preference, double veto) : this(libdesPINVOKE.new_IndifferencePreferenceVeto(indifference, preference, veto), true) {
  }

}

}
