//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DecisionWrapperCsharp {

public class MathModel : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MathModel(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MathModel obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MathModel obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~MathModel() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libdesPINVOKE.delete_MathModel(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public MathModel() : this(libdesPINVOKE.new_MathModel__SWIG_0(), true) {
  }

  public MathModel(Criterias criteriaList, EstimateVectors estimateVectorList) : this(libdesPINVOKE.new_MathModel__SWIG_1(Criterias.getCPtr(criteriaList), EstimateVectors.getCPtr(estimateVectorList)), true) {
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public MathModel(MathModel other) : this(libdesPINVOKE.new_MathModel__SWIG_2(MathModel.getCPtr(other)), true) {
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public Criterias getCriteriaList() {
    Criterias ret = new Criterias(libdesPINVOKE.MathModel_getCriteriaList(swigCPtr), true);
    return ret;
  }

  public EstimateVectors getEstimateVectorList() {
    EstimateVectors ret = new EstimateVectors(libdesPINVOKE.MathModel_getEstimateVectorList(swigCPtr), true);
    return ret;
  }

  public double sumByCriteria(int criteriaNum) {
    double ret = libdesPINVOKE.MathModel_sumByCriteria(swigCPtr, criteriaNum);
    return ret;
  }

  public double maxByCriteria(int criteriaNum) {
    double ret = libdesPINVOKE.MathModel_maxByCriteria(swigCPtr, criteriaNum);
    return ret;
  }

  public double minByCriteria(int criteriaNum) {
    double ret = libdesPINVOKE.MathModel_minByCriteria(swigCPtr, criteriaNum);
    return ret;
  }

  public bool isValid() {
    bool ret = libdesPINVOKE.MathModel_isValid(swigCPtr);
    return ret;
  }

  public bool isNormalized() {
    bool ret = libdesPINVOKE.MathModel_isNormalized(swigCPtr);
    return ret;
  }

  public void deleteEstimateVector(int vectorNum) {
    libdesPINVOKE.MathModel_deleteEstimateVector(swigCPtr, vectorNum);
  }

  public string ToString() {
    string ret = libdesPINVOKE.MathModel_ToString(swigCPtr);
    return ret;
  }

}

}
