//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class MethodsResults : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<MethodResult>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MethodsResults(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MethodsResults obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MethodsResults obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~MethodsResults() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libdesPINVOKE.delete_MethodsResults(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public MethodsResults(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (MethodResult element in c) {
      this.Add(element);
    }
  }

  public MethodsResults(global::System.Collections.Generic.IEnumerable<MethodResult> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (MethodResult element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public MethodResult this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(MethodResult[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(MethodResult[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, MethodResult[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public MethodResult[] ToArray() {
    MethodResult[] array = new MethodResult[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<MethodResult> global::System.Collections.Generic.IEnumerable<MethodResult>.GetEnumerator() {
    return new MethodsResultsEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new MethodsResultsEnumerator(this);
  }

  public MethodsResultsEnumerator GetEnumerator() {
    return new MethodsResultsEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class MethodsResultsEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<MethodResult>
  {
    private MethodsResults collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public MethodsResultsEnumerator(MethodsResults collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public MethodResult Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (MethodResult)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public MethodsResults() : this(libdesPINVOKE.new_MethodsResults__SWIG_0(), true) {
  }

  public MethodsResults(MethodsResults other) : this(libdesPINVOKE.new_MethodsResults__SWIG_1(MethodsResults.getCPtr(other)), true) {
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    libdesPINVOKE.MethodsResults_Clear(swigCPtr);
  }

  public void Add(MethodResult x) {
    libdesPINVOKE.MethodsResults_Add(swigCPtr, MethodResult.getCPtr(x));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = libdesPINVOKE.MethodsResults_size(swigCPtr);
    return ret;
  }

  private bool empty() {
    bool ret = libdesPINVOKE.MethodsResults_empty(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = libdesPINVOKE.MethodsResults_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    libdesPINVOKE.MethodsResults_reserve(swigCPtr, n);
  }

  public MethodsResults(int capacity) : this(libdesPINVOKE.new_MethodsResults__SWIG_2(capacity), true) {
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  private MethodResult getitemcopy(int index) {
    MethodResult ret = new MethodResult(libdesPINVOKE.MethodsResults_getitemcopy(swigCPtr, index), true);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private MethodResult getitem(int index) {
    MethodResult ret = new MethodResult(libdesPINVOKE.MethodsResults_getitem(swigCPtr, index), false);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, MethodResult val) {
    libdesPINVOKE.MethodsResults_setitem(swigCPtr, index, MethodResult.getCPtr(val));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(MethodsResults values) {
    libdesPINVOKE.MethodsResults_AddRange(swigCPtr, MethodsResults.getCPtr(values));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public MethodsResults GetRange(int index, int count) {
    global::System.IntPtr cPtr = libdesPINVOKE.MethodsResults_GetRange(swigCPtr, index, count);
    MethodsResults ret = (cPtr == global::System.IntPtr.Zero) ? null : new MethodsResults(cPtr, true);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, MethodResult x) {
    libdesPINVOKE.MethodsResults_Insert(swigCPtr, index, MethodResult.getCPtr(x));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, MethodsResults values) {
    libdesPINVOKE.MethodsResults_InsertRange(swigCPtr, index, MethodsResults.getCPtr(values));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    libdesPINVOKE.MethodsResults_RemoveAt(swigCPtr, index);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    libdesPINVOKE.MethodsResults_RemoveRange(swigCPtr, index, count);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public static MethodsResults Repeat(MethodResult value, int count) {
    global::System.IntPtr cPtr = libdesPINVOKE.MethodsResults_Repeat(MethodResult.getCPtr(value), count);
    MethodsResults ret = (cPtr == global::System.IntPtr.Zero) ? null : new MethodsResults(cPtr, true);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    libdesPINVOKE.MethodsResults_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    libdesPINVOKE.MethodsResults_Reverse__SWIG_1(swigCPtr, index, count);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, MethodsResults values) {
    libdesPINVOKE.MethodsResults_SetRange(swigCPtr, index, MethodsResults.getCPtr(values));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

}
