//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DecisionWrapperCsharp {

public class MethodResult : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MethodResult(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MethodResult obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MethodResult obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~MethodResult() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libdesPINVOKE.delete_MethodResult(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public MethodResult() : this(libdesPINVOKE.new_MethodResult__SWIG_0(), true) {
  }

  public MethodResult(SolveStatus first, OneStepMethod second) : this(libdesPINVOKE.new_MethodResult__SWIG_1(SolveStatus.getCPtr(first), OneStepMethod.getCPtr(second)), true) {
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public MethodResult(MethodResult other) : this(libdesPINVOKE.new_MethodResult__SWIG_2(MethodResult.getCPtr(other)), true) {
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public SolveStatus first {
    set {
      libdesPINVOKE.MethodResult_first_set(swigCPtr, SolveStatus.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = libdesPINVOKE.MethodResult_first_get(swigCPtr);
      SolveStatus ret = (cPtr == global::System.IntPtr.Zero) ? null : new SolveStatus(cPtr, false);
      return ret;
    } 
  }

  public OneStepMethod second {
    set {
      libdesPINVOKE.MethodResult_second_set(swigCPtr, OneStepMethod.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = libdesPINVOKE.MethodResult_second_get(swigCPtr);
      OneStepMethod ret = (cPtr == global::System.IntPtr.Zero) ? null : new OneStepMethod(cPtr, false);
      return ret;
    } 
  }

}

}
