//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace MultiCriteriaCsharpApi {

public class MinMaxValues : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<MinMax>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MinMaxValues(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MinMaxValues obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MinMaxValues obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~MinMaxValues() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libdesPINVOKE.delete_MinMaxValues(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public MinMaxValues(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (MinMax element in c) {
      this.Add(element);
    }
  }

  public MinMaxValues(global::System.Collections.Generic.IEnumerable<MinMax> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (MinMax element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public MinMax this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(MinMax[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(MinMax[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, MinMax[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public MinMax[] ToArray() {
    MinMax[] array = new MinMax[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<MinMax> global::System.Collections.Generic.IEnumerable<MinMax>.GetEnumerator() {
    return new MinMaxValuesEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new MinMaxValuesEnumerator(this);
  }

  public MinMaxValuesEnumerator GetEnumerator() {
    return new MinMaxValuesEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class MinMaxValuesEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<MinMax>
  {
    private MinMaxValues collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public MinMaxValuesEnumerator(MinMaxValues collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public MinMax Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (MinMax)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public MinMaxValues() : this(libdesPINVOKE.new_MinMaxValues__SWIG_0(), true) {
  }

  public MinMaxValues(MinMaxValues other) : this(libdesPINVOKE.new_MinMaxValues__SWIG_1(MinMaxValues.getCPtr(other)), true) {
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    libdesPINVOKE.MinMaxValues_Clear(swigCPtr);
  }

  public void Add(MinMax x) {
    libdesPINVOKE.MinMaxValues_Add(swigCPtr, MinMax.getCPtr(x));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = libdesPINVOKE.MinMaxValues_size(swigCPtr);
    return ret;
  }

  private bool empty() {
    bool ret = libdesPINVOKE.MinMaxValues_empty(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = libdesPINVOKE.MinMaxValues_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    libdesPINVOKE.MinMaxValues_reserve(swigCPtr, n);
  }

  public MinMaxValues(int capacity) : this(libdesPINVOKE.new_MinMaxValues__SWIG_2(capacity), true) {
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  private MinMax getitemcopy(int index) {
    MinMax ret = new MinMax(libdesPINVOKE.MinMaxValues_getitemcopy(swigCPtr, index), true);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private MinMax getitem(int index) {
    MinMax ret = new MinMax(libdesPINVOKE.MinMaxValues_getitem(swigCPtr, index), false);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, MinMax val) {
    libdesPINVOKE.MinMaxValues_setitem(swigCPtr, index, MinMax.getCPtr(val));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(MinMaxValues values) {
    libdesPINVOKE.MinMaxValues_AddRange(swigCPtr, MinMaxValues.getCPtr(values));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public MinMaxValues GetRange(int index, int count) {
    global::System.IntPtr cPtr = libdesPINVOKE.MinMaxValues_GetRange(swigCPtr, index, count);
    MinMaxValues ret = (cPtr == global::System.IntPtr.Zero) ? null : new MinMaxValues(cPtr, true);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, MinMax x) {
    libdesPINVOKE.MinMaxValues_Insert(swigCPtr, index, MinMax.getCPtr(x));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, MinMaxValues values) {
    libdesPINVOKE.MinMaxValues_InsertRange(swigCPtr, index, MinMaxValues.getCPtr(values));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    libdesPINVOKE.MinMaxValues_RemoveAt(swigCPtr, index);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    libdesPINVOKE.MinMaxValues_RemoveRange(swigCPtr, index, count);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public static MinMaxValues Repeat(MinMax value, int count) {
    global::System.IntPtr cPtr = libdesPINVOKE.MinMaxValues_Repeat(MinMax.getCPtr(value), count);
    MinMaxValues ret = (cPtr == global::System.IntPtr.Zero) ? null : new MinMaxValues(cPtr, true);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    libdesPINVOKE.MinMaxValues_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    libdesPINVOKE.MinMaxValues_Reverse__SWIG_1(swigCPtr, index, count);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, MinMaxValues values) {
    libdesPINVOKE.MinMaxValues_SetRange(swigCPtr, index, MinMaxValues.getCPtr(values));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
