//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class MultiStepMultiCriteriaMethodSolver : MultiCriteriaMethodSolver {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal MultiStepMultiCriteriaMethodSolver(global::System.IntPtr cPtr, bool cMemoryOwn) : base(libdesPINVOKE.MultiStepMultiCriteriaMethodSolver_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MultiStepMultiCriteriaMethodSolver obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MultiStepMultiCriteriaMethodSolver obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libdesPINVOKE.delete_MultiStepMultiCriteriaMethodSolver(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public MultiStepMultiCriteriaMethodSolver(MathModel mathModel, CriteriaRelation relation) : this(libdesPINVOKE.new_MultiStepMultiCriteriaMethodSolver(MathModel.getCPtr(mathModel), CriteriaRelation.getCPtr(relation)), true) {
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setMethod(MultiStepMethod method) {
    libdesPINVOKE.MultiStepMultiCriteriaMethodSolver_setMethod(swigCPtr, MultiStepMethod.getCPtr(method));
  }

  public SolveStatus getCurrentSolveStatus() {
    SolveStatus ret = new SolveStatus(libdesPINVOKE.MultiStepMultiCriteriaMethodSolver_getCurrentSolveStatus(swigCPtr), true);
    return ret;
  }

  public MathModel getMethodMathModel() {
    MathModel ret = new MathModel(libdesPINVOKE.MultiStepMultiCriteriaMethodSolver_getMethodMathModel(swigCPtr), true);
    return ret;
  }

  public MultiMethodResult solve() {
    MultiMethodResult ret = new MultiMethodResult(libdesPINVOKE.MultiStepMultiCriteriaMethodSolver_solve(swigCPtr), true);
    return ret;
  }

  public MultiMethodResult makeIteration(DecisionMakerInfo makerInfo) {
    MultiMethodResult ret = new MultiMethodResult(libdesPINVOKE.MultiStepMultiCriteriaMethodSolver_makeIteration(swigCPtr, DecisionMakerInfo.getCPtr(makerInfo)), true);
    return ret;
  }

  public IntermediateMethodData getMethodData() {
    global::System.IntPtr cPtr = libdesPINVOKE.MultiStepMultiCriteriaMethodSolver_getMethodData(swigCPtr);
    IntermediateMethodData ret = (cPtr == global::System.IntPtr.Zero) ? null : new IntermediateMethodData(cPtr, false);
    return ret;
  }

}
