//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class MultiCriteriaMethod : DecisionMakingMethod {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal MultiCriteriaMethod(global::System.IntPtr cPtr, bool cMemoryOwn) : base(libdesPINVOKE.MultiCriteriaMethod_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MultiCriteriaMethod obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MultiCriteriaMethod obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libdesPINVOKE.delete_MultiCriteriaMethod(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public virtual MathModel getMathModel() {
    MathModel ret = new MathModel(libdesPINVOKE.MultiCriteriaMethod_getMathModel(swigCPtr), true);
    return ret;
  }

  public virtual void setMathModel(MathModel mathModel) {
    libdesPINVOKE.MultiCriteriaMethod_setMathModel(swigCPtr, MathModel.getCPtr(mathModel));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void setCriteriaRelation(CriteriaRelation relation) {
    libdesPINVOKE.MultiCriteriaMethod_setCriteriaRelation(swigCPtr, CriteriaRelation.getCPtr(relation));
  }

  public virtual EstimateVector getBestEstimateVector() {
    EstimateVector ret = new EstimateVector(libdesPINVOKE.MultiCriteriaMethod_getBestEstimateVector(swigCPtr), true);
    return ret;
  }

}
