//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace MultiCriteriaCsharpApi {

public class NodesSet : global::System.IDisposable, global::System.Collections.Generic.ISet<Node>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal NodesSet(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(NodesSet obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(NodesSet obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~NodesSet() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libdesPINVOKE.delete_NodesSet(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  void global::System.Collections.Generic.ICollection<Node>.Add(Node item) {
      ((global::System.Collections.Generic.ISet<Node>)this).Add(item);
  }

  public bool TryGetValue(Node equalValue, out Node actualValue) {
    try {
      actualValue = getitem(equalValue);
      return true;
    } catch {
      actualValue = default(Node);
      return false;
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public void CopyTo(Node[] array) {
    CopyTo(array, 0);
  }

  public void CopyTo(Node[] array, int arrayIndex) {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (arrayIndex+this.Count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");

    foreach (Node item in this) {
      array.SetValue(item, arrayIndex++);
    }
  }

  public void ExceptWith(global::System.Collections.Generic.IEnumerable<Node> other) {
    foreach (Node item in other) {
      Remove(item);
    }
  }

  public void IntersectWith(global::System.Collections.Generic.IEnumerable<Node> other) {
    NodesSet old = new NodesSet(this);

    Clear();
    foreach (Node item in other) {
      if (old.Contains(item))
        Add(item);
    }
  }

  private static int count_enum(global::System.Collections.Generic.IEnumerable<Node> other) {
    int count = 0;
    foreach (Node item in other) {
      count++;
    }

    return count;
  }

  public bool IsProperSubsetOf(global::System.Collections.Generic.IEnumerable<Node> other) {
    return IsSubsetOf(other) && Count < count_enum(other);
  }

  public bool IsProperSupersetOf(global::System.Collections.Generic.IEnumerable<Node> other) {
    return IsSupersetOf(other) && Count > count_enum(other);
  }

  public bool IsSubsetOf(global::System.Collections.Generic.IEnumerable<Node> other) {
    int countContained = 0;

    foreach (Node item in other) {
      if (Contains(item))
        countContained++;
    }

    return countContained == Count;
  }

  public bool IsSupersetOf(global::System.Collections.Generic.IEnumerable<Node> other) {
    foreach (Node item in other) {
      if (!Contains(item))
        return false;
    }

    return true;
  }

  public bool Overlaps(global::System.Collections.Generic.IEnumerable<Node> other) {
    foreach (Node item in other) {
      if (Contains(item))
        return true;
    }

    return false;
  }

  public bool SetEquals(global::System.Collections.Generic.IEnumerable<Node> other) {
    return IsSupersetOf(other) && Count == count_enum(other);
  }

  public void SymmetricExceptWith(global::System.Collections.Generic.IEnumerable<Node> other) {
    foreach (Node item in other) {
      if (!Remove(item))
        Add(item);
    }
  }

  public void UnionWith(global::System.Collections.Generic.IEnumerable<Node> other) {
    foreach (Node item in other) {
      Add(item);
    }
  }

  private global::System.Collections.Generic.ICollection<Node> Items {
    get {
      global::System.Collections.Generic.ICollection<Node> items = new global::System.Collections.Generic.List<Node>();
      int size = this.Count;
      if (size > 0) {
        global::System.IntPtr iter = create_iterator_begin();
        for (int i = 0; i < size; i++) {
          items.Add(get_next(iter));
        }
        destroy_iterator(iter);
      }
      return items;
    }
  }

  global::System.Collections.Generic.IEnumerator<Node> global::System.Collections.Generic.IEnumerable<Node>.GetEnumerator() {
    return new NodesSetEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new NodesSetEnumerator(this);
  }

  public NodesSetEnumerator GetEnumerator() {
    return new NodesSetEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class NodesSetEnumerator : global::System.Collections.IEnumerator,
      global::System.Collections.Generic.IEnumerator<Node>
  {
    private NodesSet collectionRef;
    private global::System.Collections.Generic.IList<Node> ItemsCollection;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public NodesSetEnumerator(NodesSet collection) {
      collectionRef = collection;
      ItemsCollection = new global::System.Collections.Generic.List<Node>(collection.Items);
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public Node Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (Node)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = ItemsCollection[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
      currentIndex = -1;
      currentObject = null;
    }
  }


  public NodesSet() : this(libdesPINVOKE.new_NodesSet__SWIG_0(), true) {
  }

  public NodesSet(NodesSet other) : this(libdesPINVOKE.new_NodesSet__SWIG_1(NodesSet.getCPtr(other)), true) {
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = libdesPINVOKE.NodesSet_size(swigCPtr);
    return ret;
  }

  private bool empty() {
    bool ret = libdesPINVOKE.NodesSet_empty(swigCPtr);
    return ret;
  }

  public void Clear() {
    libdesPINVOKE.NodesSet_Clear(swigCPtr);
  }

  public bool Add(Node item) {
    bool ret = libdesPINVOKE.NodesSet_Add(swigCPtr, Node.getCPtr(item));
    return ret;
  }

  public bool Contains(Node item) {
    bool ret = libdesPINVOKE.NodesSet_Contains(swigCPtr, Node.getCPtr(item));
    return ret;
  }

  public bool Remove(Node item) {
    bool ret = libdesPINVOKE.NodesSet_Remove(swigCPtr, Node.getCPtr(item));
    return ret;
  }

  private Node getitem(Node item) {
    global::System.IntPtr cPtr = libdesPINVOKE.NodesSet_getitem(swigCPtr, Node.getCPtr(item));
    Node ret = (cPtr == global::System.IntPtr.Zero) ? null : new Node(cPtr, false);
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private global::System.IntPtr create_iterator_begin() {
    global::System.IntPtr ret = libdesPINVOKE.NodesSet_create_iterator_begin(swigCPtr);
    return ret;
  }

  private Node get_next(global::System.IntPtr swigiterator) {
    global::System.IntPtr cPtr = libdesPINVOKE.NodesSet_get_next(swigCPtr, swigiterator);
    Node ret = (cPtr == global::System.IntPtr.Zero) ? null : new Node(cPtr, false);
    return ret;
  }

  private void destroy_iterator(global::System.IntPtr swigiterator) {
    libdesPINVOKE.NodesSet_destroy_iterator(swigCPtr, swigiterator);
  }

}

}
