//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class OneStepMultiCriteriaMethodSolver : MultiCriteriaMethodSolver {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal OneStepMultiCriteriaMethodSolver(global::System.IntPtr cPtr, bool cMemoryOwn) : base(libdesPINVOKE.OneStepMultiCriteriaMethodSolver_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(OneStepMultiCriteriaMethodSolver obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(OneStepMultiCriteriaMethodSolver obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libdesPINVOKE.delete_OneStepMultiCriteriaMethodSolver(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public OneStepMultiCriteriaMethodSolver(MathModel mathModel, CriteriaRelation relation) : this(libdesPINVOKE.new_OneStepMultiCriteriaMethodSolver(MathModel.getCPtr(mathModel), CriteriaRelation.getCPtr(relation)), true) {
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void addMethod(OneStepMethod method) {
    libdesPINVOKE.OneStepMultiCriteriaMethodSolver_addMethod(swigCPtr, OneStepMethod.getCPtr(method));
  }

  public void addMethods(OneStepMethods methods) {
    libdesPINVOKE.OneStepMultiCriteriaMethodSolver_addMethods(swigCPtr, OneStepMethods.getCPtr(methods));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public MethodsResults solve() {
    MethodsResults ret = new MethodsResults(libdesPINVOKE.OneStepMultiCriteriaMethodSolver_solve(swigCPtr), true);
    return ret;
  }

}
