//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class PrometheeAllVersions : OneStepMethod {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal PrometheeAllVersions(global::System.IntPtr cPtr, bool cMemoryOwn) : base(libdesPINVOKE.PrometheeAllVersions_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PrometheeAllVersions obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(PrometheeAllVersions obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libdesPINVOKE.delete_PrometheeAllVersions(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public PrometheeAllVersions() : this(libdesPINVOKE.new_PrometheeAllVersions__SWIG_0(), true) {
  }

  public PrometheeAllVersions(MathModel mathModel, CriteriaRelation relation) : this(libdesPINVOKE.new_PrometheeAllVersions__SWIG_1(MathModel.getCPtr(mathModel), CriteriaRelation.getCPtr(relation)), true) {
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public void useMethodVersions(bool useI, bool useII, bool useIII) {
    libdesPINVOKE.PrometheeAllVersions_useMethodVersions(swigCPtr, useI, useII, useIII);
  }

  public void setCriterionTypes(CriterionTypes types) {
    libdesPINVOKE.PrometheeAllVersions_setCriterionTypes(swigCPtr, CriterionTypes.getCPtr(types));
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public override SolveStatus solve() {
    SolveStatus ret = new SolveStatus(libdesPINVOKE.PrometheeAllVersions_solve(swigCPtr), true);
    return ret;
  }

  public override EstimateVector getBestEstimateVector() {
    EstimateVector ret = new EstimateVector(libdesPINVOKE.PrometheeAllVersions_getBestEstimateVector(swigCPtr), true);
    return ret;
  }

}
