//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace MultiCriteriaCsharpApi {

public class SimpleCriteriaRelationUtil : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SimpleCriteriaRelationUtil(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SimpleCriteriaRelationUtil obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(SimpleCriteriaRelationUtil obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~SimpleCriteriaRelationUtil() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libdesPINVOKE.delete_SimpleCriteriaRelationUtil(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SimpleCriteriaRelationUtil(SimpleCriteriaRelation simpleCriteriaRelation) : this(libdesPINVOKE.new_SimpleCriteriaRelationUtil(SimpleCriteriaRelation.getCPtr(simpleCriteriaRelation)), true) {
  }

  public void print() {
    libdesPINVOKE.SimpleCriteriaRelationUtil_print(swigCPtr);
  }

  public AllCriteriaRelation toAllCriteriaRelation() {
    global::System.IntPtr cPtr = libdesPINVOKE.SimpleCriteriaRelationUtil_toAllCriteriaRelation(swigCPtr);
    AllCriteriaRelation ret = (cPtr == global::System.IntPtr.Zero) ? null : new AllCriteriaRelation(cPtr, false);
    return ret;
  }

  public SimpleRankingMethod toWeightCriteriaRelation() {
    global::System.IntPtr cPtr = libdesPINVOKE.SimpleCriteriaRelationUtil_toWeightCriteriaRelation(swigCPtr);
    SimpleRankingMethod ret = (cPtr == global::System.IntPtr.Zero) ? null : new SimpleRankingMethod(cPtr, false);
    return ret;
  }

}

}
