//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class SimpleCriteriaRelation : CriteriaRelation {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal SimpleCriteriaRelation(global::System.IntPtr cPtr, bool cMemoryOwn) : base(libdesPINVOKE.SimpleCriteriaRelation_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SimpleCriteriaRelation obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(SimpleCriteriaRelation obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libdesPINVOKE.delete_SimpleCriteriaRelation(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public SimpleCriteriaRelation(TwoCriteriaRelationList twoCriteriaRelations, int criteriaCount) : this(libdesPINVOKE.new_SimpleCriteriaRelation__SWIG_0(TwoCriteriaRelationList.getCPtr(twoCriteriaRelations), criteriaCount), true) {
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public SimpleCriteriaRelation(SimpleCriteriaRelation other) : this(libdesPINVOKE.new_SimpleCriteriaRelation__SWIG_1(SimpleCriteriaRelation.getCPtr(other)), true) {
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public int getCriteriaCount() {
    int ret = libdesPINVOKE.SimpleCriteriaRelation_getCriteriaCount(swigCPtr);
    return ret;
  }

  public TwoCriteriaRelationList getTwoCriteriaRelationArray() {
    TwoCriteriaRelationList ret = new TwoCriteriaRelationList(libdesPINVOKE.SimpleCriteriaRelation_getTwoCriteriaRelationArray(swigCPtr), true);
    return ret;
  }

  public override bool isValid() {
    bool ret = libdesPINVOKE.SimpleCriteriaRelation_isValid(swigCPtr);
    return ret;
  }

  public override CriteriaRelation copy() {
    global::System.IntPtr cPtr = libdesPINVOKE.SimpleCriteriaRelation_copy(swigCPtr);
    CriteriaRelation ret = (cPtr == global::System.IntPtr.Zero) ? null : new CriteriaRelation(cPtr, false);
    return ret;
  }

}
