//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class StrongAlternatives : IntermediateMethodData {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal StrongAlternatives(global::System.IntPtr cPtr, bool cMemoryOwn) : base(libdesPINVOKE.StrongAlternatives_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(StrongAlternatives obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(StrongAlternatives obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libdesPINVOKE.delete_StrongAlternatives(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public StrongAlternatives(IntList strongAlternatives) : this(libdesPINVOKE.new_StrongAlternatives(IntList.getCPtr(strongAlternatives)), true) {
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public IntList getStrongAlternatives() {
    IntList ret = new IntList(libdesPINVOKE.StrongAlternatives_getStrongAlternatives(swigCPtr), true);
    return ret;
  }

  public override string toString() {
    string ret = libdesPINVOKE.StrongAlternatives_toString(swigCPtr);
    return ret;
  }

}
