//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DecisionWrapperCsharp {

public class SuccessiveConcessionsIntermediateData : IntermediateMethodData {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal SuccessiveConcessionsIntermediateData(global::System.IntPtr cPtr, bool cMemoryOwn) : base(libdesPINVOKE.SuccessiveConcessionsIntermediateData_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SuccessiveConcessionsIntermediateData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(SuccessiveConcessionsIntermediateData obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libdesPINVOKE.delete_SuccessiveConcessionsIntermediateData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public SuccessiveConcessionsIntermediateData(Criteria criteriaThatNeedCedeValue) : this(libdesPINVOKE.new_SuccessiveConcessionsIntermediateData(Criteria.getCPtr(criteriaThatNeedCedeValue)), true) {
    if (libdesPINVOKE.SWIGPendingException.Pending) throw libdesPINVOKE.SWIGPendingException.Retrieve();
  }

  public Criteria getCriteriaThatNeedCedeValue() {
    Criteria ret = new Criteria(libdesPINVOKE.SuccessiveConcessionsIntermediateData_getCriteriaThatNeedCedeValue(swigCPtr), true);
    return ret;
  }

  public override string toString() {
    string ret = libdesPINVOKE.SuccessiveConcessionsIntermediateData_toString(swigCPtr);
    return ret;
  }

}

}
