//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DecisionWrapperCsharp {

public class WeightCriteriaRelation : CriteriaRelation {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal WeightCriteriaRelation(global::System.IntPtr cPtr, bool cMemoryOwn) : base(libdesPINVOKE.WeightCriteriaRelation_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(WeightCriteriaRelation obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(WeightCriteriaRelation obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libdesPINVOKE.delete_WeightCriteriaRelation(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public virtual WeightMap getCriteriaWeightMap() {
    WeightMap ret = new WeightMap(libdesPINVOKE.WeightCriteriaRelation_getCriteriaWeightMap(swigCPtr), true);
    return ret;
  }

  public virtual int getCriteriaCount() {
    int ret = libdesPINVOKE.WeightCriteriaRelation_getCriteriaCount(swigCPtr);
    return ret;
  }

  public override bool isValid() {
    bool ret = libdesPINVOKE.WeightCriteriaRelation_isValid(swigCPtr);
    return ret;
  }

  public override CriteriaRelation copy() {
    global::System.IntPtr cPtr = libdesPINVOKE.WeightCriteriaRelation_copy(swigCPtr);
    CriteriaRelation ret = (cPtr == global::System.IntPtr.Zero) ? null : new CriteriaRelation(cPtr, false);
    return ret;
  }

}

}
